name: continuous-integration-continuous-delivery
on:
  push:
   branches: ['main']
  workflow_dispatch:

jobs: 
#   job-build:
#     runs-on: ubuntu-latest

#     steps: 
#     - name: checkout repository
#       uses: actions/checkout@v4.1.7
#     - name: using node
#       uses: actions/setup-node@v4.0.3
#       with: 
#         node-version: 22.x
#     - name: run 
#       run: | 
#         npm install
#         npm run build
#     - name: upload artefacts
#       uses: actions/upload-artifact@v4.3.4
#       with:
#         name: artifact
#         path: .


  job-build:

    name: "build"
    uses: enzoovizotto/ci-cd/.github/workflows/build_reutilizavel.yml@main
    with: 
      node-version: 20



  job-deploy:
    needs: job-build

    name: deploy
    uses: enzoovizotto/ci-cd/.github/workflows/deploy_reutilizavel.yml@main
    with:
      environment: production
      app-name: "ci-cd-enzo"
      publish-profile: "AZURE_PUBLISH_PROFILE"
    secrets:
      publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}


        
  
