name: continuous-integration-continuous-delivery
on:
  push:
   branches: ['main']

jobs: 
#   job-build:
#     runs-on: ubuntu-latest

#     steps: 
#     - name: checkout repository
#       uses: actions/checkout@v4.1.7
#     - name: using node
#       uses: actions/setup-node@v4.0.3
#       with: 
#         node-version: 22.x
#     - name: run 
#       run: | 
#         npm install
#         npm run build
#     - name: upload artefacts
#       uses: actions/upload-artifact@v4.3.4
#       with:
#         name: artifact
#         path: .


  job-build:
    runs-on: ubuntu-latest

    steps: 
    - name: run build
      uses: ./enzoovizotto/ci-cd/.github/workflows/build_reutilizavel.yml@main
      with: 
        node-version: 20



  job-deploy:
    runs-on: ubuntu-latest
    needs: job-build

    steps: 
    - name: deploy
      uses: ./enzoovizotto/ci-cd/.github/workflows/deploy_reutilizavel.yml@main
      with:
        name: artifact
        enviroment: production
        app-name: "ci-cd-enzo"
        publish-profile: ${{secrets.azure_publish_profile}}


        
  
